const LIGHT_COLOR = '#FFFFFF';
const DARK_COLOR = '#000000';
const ACCENT_COLOR = '#FF70A6';

const HORIZONTAL_SPACE = '100px';
const VERTICAL_SPACE = '40px';
const MOBILE_VIEW_WIDTH = 980;

const FONT_SIZE = '72px';

const LIGHT_FONT = 'NoiGrotesk-Light';
const DARK_FONT = 'NoiGrotesk-Semibold';
const CONDENSED_FONT = 'PPFormula-CondensedBlack';

const ANIMATION_DURATION = 0.3;

const MAX_Z_INDEX = 99;

export {
  LIGHT_COLOR,
  DARK_COLOR,
  ACCENT_COLOR,
  HORIZONTAL_SPACE,
  VERTICAL_SPACE,
  FONT_SIZE,
  ANIMATION_DURATION,
  MAX_Z_INDEX,
  LIGHT_FONT,
  DARK_FONT,
  CONDENSED_FONT,
  MOBILE_VIEW_WIDTH,
};
