const LIGHT_COLOR = '#FFFFFF';
const DARK_COLOR = '#000000';
const ACCENT_COLOR = '#FF70A6';
const GREY_COLOR = '#555555';
const LIGHT_GREY_COLOR = '#dddddd';
const LIGHT_DARK_COLOR = '#444444';
const BORDER_DARK_COLOR = '#222222';

const HORIZONTAL_SPACE = '100px';
const VERTICAL_SPACE = '40px';
const MOBILE_VIEW_WIDTH = 980;

const FONT_SIZE = '72px';

const LIGHT_FONT = 'NoiGrotesk-Light';
const DARK_FONT = 'NoiGrotesk-Semibold';
const CONDENSED_FONT = 'PPFormula-CondensedBlack';

const ANIMATION_DURATION = 0.3;

const MAX_Z_INDEX = 99;

export {
    ACCENT_COLOR,
    ANIMATION_DURATION, BORDER_DARK_COLOR, CONDENSED_FONT,
    DARK_COLOR,
    DARK_FONT,
    FONT_SIZE, GREY_COLOR, HORIZONTAL_SPACE,
    LIGHT_COLOR, LIGHT_DARK_COLOR, LIGHT_FONT, LIGHT_GREY_COLOR, MAX_Z_INDEX,
    MOBILE_VIEW_WIDTH,
    VERTICAL_SPACE
};

