const LIGHT_COLOR = '#FFFFFF';
const DARK_COLOR = '#000000';
const ACCENT_COLOR = '#FF70A6';

const HORIZONTAL_SPACE = '100px';
const VERTICAL_SPACE = '40px';

const FONT_SIZE = '72px';

const ANIMATION_DURATION = 0.3;

const MAX_Z_INDEX = 99;

export {
  LIGHT_COLOR,
  DARK_COLOR,
  ACCENT_COLOR,
  HORIZONTAL_SPACE,
  VERTICAL_SPACE,
  FONT_SIZE,
  ANIMATION_DURATION,
  MAX_Z_INDEX,
};
